### ISSUE TITLE
Go build is complaining about missing charly/gitea|gogs

### ISSUE THREAD

**Issue by Thulium-Drake** [cooperspencer/charly#1]
Hi!

When I try building it, it seems that it's complaining about some missing files for Gogs and Gitea:

```
main.go:5:2: package charly/gitea is not in GOROOT (/opt/go/src/charly/gitea)
main.go:8:2: package charly/gogs is not in GOROOT (/opt/go/src/charly/gogs)
```

I use a custom compiled version of Go, but the same setup did work for compiling gickup :-)

**Comment by cooperspencer** [comment]
Hi,
Sorry, I forgot to push those two modules. can you try it again?

**Comment by cooperspencer** [comment]
I changed quite a bit in the code, the configuration file has changed.
But it should now work with every code versioning system, not just github, gitea, gogs and gitlab

**Comment by Thulium-Drake** [comment]
Cool, thanks! It did build after your last changes, but I'm building a fresh copy now :-)

**Comment by Thulium-Drake** [comment]
Works like a charm! Thank you very much!

One question, can you make the ```script``` section also multilevel? So that I can just run the same script for a whole list of repos? :)

**Comment by Thulium-Drake** [comment]
I now run with the following config, might be useful as an example:

```
gitea:
  working-dir: /home/jeff/backup-git
  auth:
    token: my-secret-token
    ssh-keyfile: /home/jeff/.ssh/id_git_backup
    username: jeff
  repos:
    - url: https://git.example.com/Ansible/role-sshd
      script: |+
        if [ -d "$REPO" ]; then
          cd $REPO
          git pull origin $BRANCH
          git push -u github $BRANCH
        else
          git clone ssh://git@git.example.com/Ansible/$REPO
          cd $REPO
          git remote add github ssh://git@github.com/thulium-drake/ansible-$REPO
          git push github $BRANCH
        fi

```

**Comment by cooperspencer** [comment]
Glad to hear that 😁
That's something I want to implement next. I will notify you as soon as I implement it.

**Comment by cooperspencer** [comment]
I implemented it. You can check out the example config to see how it works.

**Comment by Thulium-Drake** [comment]
Cool, works like a charm! Thanks!
