### ISSUE TITLE
Pull all branches from the repo?

### ISSUE THREAD

**Issue by Eyeless77** [cooperspencer/charly#4]
Hello!

Is there any option to pull all branches from a source repo? By default it grabs only default branch (except the case when the branch is defined explicitly in config file), but there may be dozens of remote branches.

**Comment by cooperspencer** [comment]
Hi,

This is currently not supported but I'll have a look into it.

**Comment by cooperspencer** [comment]
I implemented an 'allbranches' key in the config. It should now work with all branches.

**Comment by Eyeless77** [comment]
Works great! Thank you!
